version: "3.4"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "initiative"



  initiative-service:
    image: abhissaw/initiative-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/initiative"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
    depends_on:
      - postgres

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  myredis:
    image: redis
    ports:
      - "6379:6379"
  plan-service:
    image: abhissaw/plan-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongo/plan"
      INITIATIVE_SERVICE_URL: "http://initiative-service:8081"
      SPRING_DATA_REDIS_HOST: "myredis"


    depends_on:
      - initiative-service
      - mongo
      - myredis